# Generated by Django 3.1 on 2020-10-27 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('diaUri', models.CharField(blank=True, max_length=200, null=True)),
                ('noDiaUri', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VmColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('html', models.TextField()),
                ('minH', models.IntegerField()),
                ('minW', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('vManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('webhookId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vmanager')),
            ],
        ),
        migrations.AddField(
            model_name='vmanager',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vmcolor'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('users', models.ManyToManyField(related_name='userGp', to='monitor.User')),
                ('vManagers', models.ManyToManyField(related_name='vmGp', to='monitor.VManager')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.CharField(max_length=200)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.webhook')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.user')),
                ('widgets', models.ManyToManyField(through='monitor.Component', to='monitor.Widget')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.dashboard'),
        ),
        migrations.AddField(
            model_name='component',
            name='vManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vmanager'),
        ),
        migrations.AddField(
            model_name='component',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.widget'),
        ),
    ]
