# Generated by Django 3.0.7 on 2020-07-14 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('html', models.TextField()),
                ('minH', models.IntegerField()),
                ('minW', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User')),
                ('widgets', models.ManyToManyField(through='monitor.Component', to='monitor.Widget')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Dashboard'),
        ),
        migrations.AddField(
            model_name='component',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Widget'),
        ),
    ]
