# Generated by Django 3.0.7 on 2020-07-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200714_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='VManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
        migrations.AddField(
            model_name='component',
            name='vManager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monitor.VManager'),
            preserve_default=False,
        ),
    ]
