# Generated by Django 3.0.7 on 2020-09-15 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20200715_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmanager',
            name='diaUri',
            field=models.CharField(default='no existe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmanager',
            name='noDiaUri',
            field=models.CharField(default='no existe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmanager',
            name='webhookId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
    ]
