# Generated by Django 3.0.7 on 2020-09-24 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20200920_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='message',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='time',
        ),
        migrations.AddField(
            model_name='webhook',
            name='webhookId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
    ]
