# Generated by Django 3.0.7 on 2020-09-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200924_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmanager',
            name='webhookId',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
        migrations.AlterField(
            model_name='vmanager',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.VmColor'),
        ),
        migrations.AlterField(
            model_name='vmanager',
            name='diaUri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmanager',
            name='noDiaUri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
