# Generated by Django 3.0.7 on 2020-09-30 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20200930_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='userGp', to='monitor.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='vManagers',
            field=models.ManyToManyField(related_name='vmGp', to='monitor.VManager'),
        ),
    ]
