# Generated by Django 3.0.7 on 2020-10-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20200930_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='userGp', to='monitor.User'),
        ),
        migrations.CreateModel(
            name='ExcludeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.CharField(max_length=200)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Webhook')),
            ],
        ),
    ]
