# Generated by Django 3.0.7 on 2020-10-27 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20201002_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='message',
            field=models.CharField(default='no message :(', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='vManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.VManager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='userGp', to='monitor.User'),
        ),
    ]
