# Generated by Django 3.0.7 on 2020-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20201105_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='inDia',
            field=models.BooleanField(default=True),
        ),
    ]
